"""add learning sessions table

Revision ID: e372adbd2a34
Revises: b4a6a8392c07
Create Date: 2026-09-08 07:24:13.643969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e372adbd2a34'
down_revision: Union[str, Sequence[str], None] = 'b4a6a8392c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='Planned', nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('focus', sa.String(length=500), nullable=False),
    sa.Column('learned', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('tomorrow_priority', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_session_date'), 'learning_sessions', ['session_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_sessions_session_date'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
